In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import itertools as it

In [2]:
data = pd.read_csv('/Users/pavelfilchenkov/Desktop/movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
557,tt0221218,30000000,23619609,The Glass House,Leelee Sobieski|Diane Lane|Stellan SkarsgÃ¥rd|...,Daniel Sackheim,The glass is about to be shattered...,After the parents of Ruby and her younger brot...,106,Drama|Thriller,Original Film,9/14/2001,5.3,2001
1415,tt0388980,25000000,15431177,The Greatest Game Ever Played,Shia LaBeouf|Stephen Dillane|Josh Flitter|Pete...,Bill Paxton,Based on a True Story,A biopic of 20-year-old Francis Ouimet who def...,120,Drama|Family,Walt Disney Pictures,9/30/2005,7.0,2005
1407,tt0379725,7000000,49084830,Capote,Philip Seymour Hoffman|Allie Mickelson|Craig A...,Bennett Miller,In Cold Blood,"A biopic of the writer, Truman Capote and his ...",114,Crime|Drama,Sony Pictures Classics|Cooper's Town Productio...,9/30/2005,6.7,2005
246,tt1136608,30000000,210819611,District 9,Sharlto Copley|Jason Cope|Nathalie Boltt|Sylva...,Neill Blomkamp,You are not welcome here.,Aliens land in South Africa and have no way ho...,112,Action|Thriller|Science Fiction,WingNut Films|TriStar Pictures|Key Creatives|B...,8/5/2009,7.1,2009
1128,tt0348836,40000000,141591324,Gothika,Halle Berry|Robert Downey Jr.|Charles S. Dutto...,Mathieu Kassovitz,Because someone is dead doesn't mean they're g...,"After a car crash, a criminal psychologist (Ha...",98,Horror|Thriller,Columbia Pictures Corporation|Dark Castle Ente...,11/21/2003,5.8,2003

In [3]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [4]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

In [5]:
data.head(10)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015
5,tt1663202,135000000,532950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,Alejandro GonzÃ¡lez IÃ±Ã¡rritu,"(n. One who has returned, as if from the dead.)","In the 1820s, a frontiersman, Hugh Glass, sets...",156,Western|Drama|Adventure|Thriller,Regency Enterprises|Appian Way|CatchPlay|Anony...,12/25/2015,7.2,2015
6,tt1340138,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,Alan Taylor,Reset the future,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,6/23/2015,5.8,2015
7,tt3659388,108000000,595380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,Ridley Scott,Bring Him Home,"During a manned mission to Mars, Astronaut Mar...",141,Drama|Adventure|Science Fiction,Twentieth Century Fox Film Corporation|Scott F...,9/30/2015,7.6,2015
8,tt2293640,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses","Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,6/17/2015,6.5,2015
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015

In [6]:
data.dtypes

imdb_id                  object
budget                    int64
revenue                   int64
original_title           object
cast                     object
director                 object
tagline                  object
overview                 object
runtime                   int64
genres                   object
production_companies     object
release_date             object
vote_average            float64
release_year              int64
dtype: object

In [7]:
data2 = data.copy()
data2['cast'] = data2.cast.str.split('|')
data2['director'] = data2.director.str.split('|')
data2['genres'] = data2.genres.str.split('|')
data2['production_companies'] = data2.production_companies.str.split('|')
data2['release_date'] = pd.to_datetime(data2['release_date'])
data2

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,"[Chris Pratt, Bryce Dallas Howard, Irrfan Khan...",[Colin Trevorrow],The park is open.,Twenty-two years after the events of Jurassic ...,124,"[Action, Adventure, Science Fiction, Thriller]","[Universal Studios, Amblin Entertainment, Lege...",2015-06-09,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,"[Tom Hardy, Charlize Theron, Hugh Keays-Byrne,...",[George Miller],What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,"[Action, Adventure, Science Fiction, Thriller]","[Village Roadshow Pictures, Kennedy Miller Pro...",2015-05-13,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,"[Shailene Woodley, Theo James, Kate Winslet, A...",[Robert Schwentke],One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,"[Adventure, Science Fiction, Thriller]","[Summit Entertainment, Mandeville Films, Red W...",2015-03-18,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,"[Harrison Ford, Mark Hamill, Carrie Fisher, Ad...",[J.J. Abrams],Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,"[Action, Adventure, Science Fiction, Fantasy]","[Lucasfilm, Truenorth Productions, Bad Robot]",2015-12-15,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,"[Vin Diesel, Paul Walker, Jason Statham, Miche...",[James Wan],Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,"[Action, Crime, Thriller]","[Universal Pictures, Original Film, Media Righ...",2015-04-01,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,tt0120903,75000000,157299717,X-Men,"[Patrick Stewart, Hugh Jackman, Ian McKellen, ...",[Bryan Singer],Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,"[Adventure, Action, Science Fiction]","[Twentieth Century Fox Film Corporation, Donne...",2000-07-13,6.6,2000
1885,tt0192255,22000000,13555988,The Little Vampire,"[Richard E. Grant, Jonathan Lipnicki, Jim Cart...",[Uli Edel],"They're not just best friends, they're blood b...","Based on the popular books, the story tells of...",95,"[Horror, Family, Foreign]",[New Line Cinema],2000-10-27,6.4,2000
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,"[Rene Russo, Jason Alexander, Piper Perabo, Ra...",[Des McAnuff],This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,"[Adventure, Animation, Action, Comedy, Family]","[Universal Pictures, Capella International, KC...",2000-06-30,4.0,2000
1887,tt0162983,40000000,36037909,Hanging Up,"[Meg Ryan, Diane Keaton, Lisa Kudrow, Walter M...",[Diane Keaton],Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,"[Comedy, Drama]","[Laurence Mark Productions, Columbia Pictures ...",2000-02-16,5.2,2000
1888,tt0163676,15000000,5217498,The In Crowd,"[Susan Ward, Lori Heuring, Matthew Settle, Nat...",[Mary Lambert],What would you do to get in?,A mentally disturbed young woman takes a job a...,105,[Thriller],[Warner Bros. Pictures],2000-07-19,5.2,2000

In [8]:
data2.dtypes

imdb_id                         object
budget                           int64
revenue                          int64
original_title                  object
cast                            object
director                        object
tagline                         object
overview                        object
runtime                          int64
genres                          object
production_companies            object
release_date            datetime64[ns]
vote_average                   float64
release_year                     int64
dtype: object

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.
Вы думаете и в жизни у вас будут варианты ответов?)

In [9]:
# в словарь вставляем номер вопроса и ваш ответ на него
answers['1'] = '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)'

In [10]:
# тут пишем ваш код для решения данного вопроса:
d1 = data[data['budget'] == data['budget'].max()]
d1

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011

ВАРИАНТ 2

In [11]:
data.loc[data.budget == data.budget.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011

# 2. Какой из фильмов самый длительный (в минутах)?

In [12]:
answers['2'] = '2. Gods and Generals  (tt0279111)'

In [13]:
# Вариант 1
d2 = data[data['runtime'] == data['runtime'].max()]
d2

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003

ВАРИАНТ 2

In [14]:
# Вариант 2
data.loc[data.runtime == data.runtime.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003

# 3. Какой из фильмов самый короткий (в минутах)?

In [15]:
answers['3'] = '3. Winnie the Pooh (tt1449283)'

In [16]:
data.loc[data.runtime == data.runtime.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011

# 4. Какова средняя длительность фильмов?

In [17]:
answers['4'] = '2. 110'

In [18]:
data.runtime.mean()

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [19]:
answers['5'] = '1. 107'

In [20]:
data.runtime.median()

107.0

# 6. Какой самый прибыльный фильм?

**Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)**

In [21]:
# лучше код получения столбца profit вынести в Предобработку что в начале

In [22]:
answers['6'] = '5. Avatar (tt0499549)'

In [23]:
data2['profit'] = data2['revenue'] - data2['budget']
data2

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
0,tt0369610,150000000,1513528810,Jurassic World,"[Chris Pratt, Bryce Dallas Howard, Irrfan Khan...",[Colin Trevorrow],The park is open.,Twenty-two years after the events of Jurassic ...,124,"[Action, Adventure, Science Fiction, Thriller]","[Universal Studios, Amblin Entertainment, Lege...",2015-06-09,6.5,2015,1363528810
1,tt1392190,150000000,378436354,Mad Max: Fury Road,"[Tom Hardy, Charlize Theron, Hugh Keays-Byrne,...",[George Miller],What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,"[Action, Adventure, Science Fiction, Thriller]","[Village Roadshow Pictures, Kennedy Miller Pro...",2015-05-13,7.1,2015,228436354
2,tt2908446,110000000,295238201,Insurgent,"[Shailene Woodley, Theo James, Kate Winslet, A...",[Robert Schwentke],One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,"[Adventure, Science Fiction, Thriller]","[Summit Entertainment, Mandeville Films, Red W...",2015-03-18,6.3,2015,185238201
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,"[Harrison Ford, Mark Hamill, Carrie Fisher, Ad...",[J.J. Abrams],Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,"[Action, Adventure, Science Fiction, Fantasy]","[Lucasfilm, Truenorth Productions, Bad Robot]",2015-12-15,7.5,2015,1868178225
4,tt2820852,190000000,1506249360,Furious 7,"[Vin Diesel, Paul Walker, Jason Statham, Miche...",[James Wan],Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,"[Action, Crime, Thriller]","[Universal Pictures, Original Film, Media Righ...",2015-04-01,7.3,2015,1316249360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,tt0120903,75000000,157299717,X-Men,"[Patrick Stewart, Hugh Jackman, Ian McKellen, ...",[Bryan Singer],Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,"[Adventure, Action, Science Fiction]","[Twentieth Century Fox Film Corporation, Donne...",2000-07-13,6.6,2000,82299717
1885,tt0192255,22000000,13555988,The Little Vampire,"[Richard E. Grant, Jonathan Lipnicki, Jim Cart...",[Uli Edel],"They're not just best friends, they're blood b...","Based on the popular books, the story tells of...",95,"[Horror, Family, Foreign]",[New Line Cinema],2000-10-27,6.4,2000,-8444012
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,"[Rene Russo, Jason Alexander, Piper Perabo, Ra...",[Des McAnuff],This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,"[Adventure, Animation, Action, Comedy, Family]","[Universal Pictures, Capella International, KC...",2000-06-30,4.0,2000,-40865180
1887,tt0162983,40000000,36037909,Hanging Up,"[Meg Ryan, Diane Keaton, Lisa Kudrow, Walter M...",[Diane Keaton],Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,"[Comedy, Drama]","[Laurence Mark Productions, Columbia Pictures ...",2000-02-16,5.2,2000,-3962091
1888,tt0163676,15000000,5217498,The In Crowd,"[Susan Ward, Lori Heuring, Matthew Settle, Nat...",[Mary Lambert],What would you do to get in?,A mentally disturbed young woman takes a job a...,105,[Thriller],[Warner Bros. Pictures],2000-07-19,5.2,2000,-9782502

In [24]:
data2.loc[data2.profit == data2.profit.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,"[Action, Adventure, Fantasy, Science Fiction]","[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,7.1,2009,2544505847

# 7. Какой фильм самый убыточный?

In [25]:
answers['7'] = '5. The Lone Ranger  (tt1210819)'

In [26]:
data2.loc[data2.profit == data2.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,"[Johnny Depp, Armie Hammer, William Fichtner, ...",[Gore Verbinski],Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,"[Action, Adventure, Western]","[Walt Disney Pictures, Jerry Bruckheimer Films...",2013-07-03,6.0,2013,-165710090

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [27]:
answers['8'] = '1. 1478 '

In [28]:
data.loc[data.revenue > data.budget]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,tt0171433,30000000,37036004,Keeping the Faith,Ben Stiller|Edward Norton|Jenna Elfman|Anne Ba...,Edward Norton,"If you have to believe in something, you may a...","Best friends since they were kids, Rabbi Jacob...",127,Comedy,Spyglass Entertainment|Touchstone Pictures|Tri...,4/14/2000,5.7,2000
1875,tt0219854,65000000,69700000,The Kid,Bruce Willis|Spencer Breslin|Emily Mortimer|Li...,Jon Turteltaub,Nobody ever grows up quite like they imagined.,Powerful businessman Russ Duritz is self-absor...,104,Fantasy|Comedy|Family,Walt Disney Pictures,7/7/2000,5.9,2000
1877,tt0199725,20000000,27728118,Love & Basketball,"Chris Warren, Jr.|Kyla Pratt|Sanaa Lathan|Omar...",Gina Prince-Bythewood,All's fair in love and basketball.,A young African-American couple navigates the ...,124,Action|Comedy|Drama|Romance,40 Acres & A Mule Filmworks,4/21/2000,7.3,2000
1883,tt0122459,24000000,36609995,Return to Me,David Duchovny|Minnie Driver|Carroll O'Connor|...,Bonnie Hunt,A comedy straight from the heart,It took a lot of cajoling to get Bob (Duchovny...,115,Romance|Comedy|Drama,Metro-Goldwyn-Mayer (MGM)|JLT Productions,4/7/2000,5.5,2000
1884,tt0120903,75000000,157299717,X-Men,Patrick Stewart|Hugh Jackman|Ian McKellen|Hall...,Bryan Singer,Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,Adventure|Action|Science Fiction,Twentieth Century Fox Film Corporation|Donners...,7/13/2000,6.6,2000

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [29]:
answers['9'] = '4. The Dark Knight (tt0468569)'

In [30]:
d3 = data.loc[data.release_year == 2008]
d3

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
600,tt0910970,180000000,521311860,WALLÂ·E,Ben Burtt|Elissa Knight|Jeff Garlin|Fred Willa...,Andrew Stanton,An adventure beyond the ordinar-E.,WALLÂ·E is the last robot left on an Earth tha...,98,Animation|Family,Walt Disney Pictures|Pixar Animation Studios,6/22/2008,7.6,2008
601,tt0371746,140000000,585174222,Iron Man,Robert Downey Jr.|Terrence Howard|Jeff Bridges...,Jon Favreau,Heroes aren't born. They're built.,"After being held captive in an Afghan cave, bi...",126,Action|Science Fiction|Adventure,Marvel Studios,4/30/2008,7.3,2008
602,tt0936501,25000000,226830568,Taken,Liam Neeson|Famke Janssen|Maggie Grace|Katie C...,Pierre Morel,They took his daughter. He'll take their lives.,"While vacationing with a friend in Paris, an A...",93,Action|Thriller|Crime,Twentieth Century Fox Film Corporation|M6 Film...,2/18/2008,7.2,2008
603,tt0367882,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,5.6,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,tt0858479,7000000,10569964,Smart People,Dennis Quaid|Sarah Jessica Parker|Ellen Page|T...,Noam Murro,Sometimes the smartest people have the most to...,Professor Lawrence Wetherhold (Dennis Quaid) m...,95,Comedy|Drama|Romance,Miramax Films|Sherazade Film Development|Groun...,4/11/2008,5.5,2008
716,tt0410377,37000000,100076342,Nim's Island,Abigail Breslin|Jodie Foster|Gerard Butler|Mic...,Jennifer Flackett|Mark Levin,Your adventure starts here.,A young girl inhabits an isolated island with ...,96,Adventure|Comedy|Family|Fantasy,Walden Media,4/3/2008,5.5,2008
717,tt0465502,25000000,30000000,Igor,John Cusack|Myleene Klass|Robin Walsh|Matt McK...,Anthony Leondis,All men aren't created Evil.,Animated fable about a clichÃ© hunchbacked evi...,87,Animation|Comedy|Family|Fantasy,Exodus Film Group|Exodus Productions,9/19/2008,5.4,2008
718,tt0455538,27000000,17286299,How to Lose Friends & Alienate People,Kelan Pannell|Janette Scott|Simon Pegg|Megan F...,Robert B. Weide,"He's across the pond, and out of his depth.",A British writer struggles to fit in at a high...,110,Comedy|Romance|Drama,UK Film Council|Intandem Films|Aramid Entertai...,10/2/2008,6.0,2008
719,tt0494652,35000000,43650785,Welcome Home Roscoe Jenkins,Martin Lawrence|James Earl Jones|Margaret Aver...,Malcolm D. Lee,Roscoe Jenkins aims for the heartstrings and f...,"Martin Lawrence leads an all-star cast, includ...",114,Comedy|Drama,Universal Pictures|Spyglass Entertainment,2/8/2008,6.1,2008

In [31]:
d3.loc[d3.revenue == d3.revenue.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [32]:
answers['10'] = '5. The Lone Ranger (tt1210819)'

In [33]:
d4 = data2.loc[(data2.release_year > 2011) & (data2.release_year < 2015)]
d4

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
118,tt0816692,165000000,621752480,Interstellar,"[Matthew McConaughey, Jessica Chastain, Anne H...",[Christopher Nolan],Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,"[Adventure, Drama, Science Fiction]","[Paramount Pictures, Legendary Pictures, Warne...",2014-11-05,8.0,2014,456752480
119,tt2015381,170000000,773312399,Guardians of the Galaxy,"[Chris Pratt, Zoe Saldana, Dave Bautista, Vin ...",[James Gunn],All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,"[Action, Science Fiction, Adventure]","[Marvel Studios, Moving Picture Company (MPC),...",2014-07-30,7.9,2014,603312399
120,tt1843866,170000000,714766572,Captain America: The Winter Soldier,"[Chris Evans, Scarlett Johansson, Sebastian St...","[Joe Russo, Anthony Russo]",In heroes we trust.,After the cataclysmic events in New York with ...,136,"[Action, Adventure, Science Fiction]",[Marvel Studios],2014-03-20,7.6,2014,544766572
121,tt2911666,20000000,78739897,John Wick,"[Keanu Reeves, Michael Nyqvist, Alfie Allen, W...","[Chad Stahelski, David Leitch]",Don't set him off.,"After the sudden death of his beloved wife, Jo...",101,"[Action, Thriller]","[Thunder Road Pictures, Warner Bros., 87Eleven...",2014-10-22,7.0,2014,58739897
122,tt1951265,125000000,752100229,The Hunger Games: Mockingjay - Part 1,"[Jennifer Lawrence, Josh Hutcherson, Liam Hems...",[Francis Lawrence],Fire burns brighter in the darkness,Katniss Everdeen reluctantly becomes the symbo...,123,"[Science Fiction, Adventure, Thriller]","[Lionsgate, Color Force]",2014-11-18,6.6,2014,627100229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,tt2431286,12000000,100129872,Philomena,"[Judi Dench, Steve Coogan, Sophie Kennedy Clar...",[Stephen Frears],These two unlikely companions are on a journey...,"A woman searches for her adult son, who was ta...",98,[Drama],"[BBC Films, The Weinstein Company, Baby Cow Pr...",2013-11-01,7.4,2013,88129872
1308,tt1758595,15000000,21766271,Diana,"[Naomi Watts, Naveen Andrews, Charles Edwards,...",[Oliver Hirschbiegel],The legend is never the whole story,"During the last two years of her life, Princes...",113,"[Drama, Romance]","[Ecosse Films, Le Pacte, Scope Pictures, Film ...",2013-09-19,5.0,2013,6766271
1309,tt2167202,18000000,10501938,Getaway,"[Ethan Hawke, Selena Gomez, Jon Voight, Paul F...",[Courtney Solomon],Get in. Get out. Getaway.,Former race car driver Brent Magna (Hawke) is ...,90,"[Action, Crime]","[Dark Castle Entertainment, Signature Pictures...",2013-08-29,5.0,2013,-7498062
1310,tt2234155,58000000,44000000,The Internship,"[Owen Wilson, Vince Vaughn, Tiya Sircar, Rose ...",[Shawn Levy],Hiring them was a brilliant mistake.,Two recently laid-off men in their 40s try to ...,119,[Comedy],"[Twentieth Century Fox Film Corporation, Regen...",2013-06-07,6.1,2013,-14000000
1311,tt1966566,30000000,68129518,Ð¡Ñ‚Ð°Ð»Ð¸Ð½Ð³Ñ€Ð°Ð´,"[Thomas Kretschmann, Yanina Studilina, Philipp...",[Fyodor Bondarchuk],The Epic Battle That Turned The Tide Of World ...,"Drama set in 1942, during one of the most impo...",131,"[War, Action]",[Art Pictures Studio],2013-10-09,5.5,2013,38129518

In [34]:
d4.loc[d4.profit == d4.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,"[Johnny Depp, Armie Hammer, William Fichtner, ...",[Gore Verbinski],Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,"[Action, Adventure, Western]","[Walt Disney Pictures, Jerry Bruckheimer Films...",2013-07-03,6.0,2013,-165710090

# 11. Какого жанра фильмов больше всего?

In [35]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале

In [36]:
 answers['11'] = '3. Drama'

In [37]:
data2.explode('genres').groupby('genres')['imdb_id'].count().sort_values(ascending = False)

genres
Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
Name: imdb_id, dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [38]:
 answers['12'] = '1. Drama'

In [39]:
d5 = data2[data2['profit'] > 0]
d5

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
0,tt0369610,150000000,1513528810,Jurassic World,"[Chris Pratt, Bryce Dallas Howard, Irrfan Khan...",[Colin Trevorrow],The park is open.,Twenty-two years after the events of Jurassic ...,124,"[Action, Adventure, Science Fiction, Thriller]","[Universal Studios, Amblin Entertainment, Lege...",2015-06-09,6.5,2015,1363528810
1,tt1392190,150000000,378436354,Mad Max: Fury Road,"[Tom Hardy, Charlize Theron, Hugh Keays-Byrne,...",[George Miller],What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,"[Action, Adventure, Science Fiction, Thriller]","[Village Roadshow Pictures, Kennedy Miller Pro...",2015-05-13,7.1,2015,228436354
2,tt2908446,110000000,295238201,Insurgent,"[Shailene Woodley, Theo James, Kate Winslet, A...",[Robert Schwentke],One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,"[Adventure, Science Fiction, Thriller]","[Summit Entertainment, Mandeville Films, Red W...",2015-03-18,6.3,2015,185238201
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,"[Harrison Ford, Mark Hamill, Carrie Fisher, Ad...",[J.J. Abrams],Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,"[Action, Adventure, Science Fiction, Fantasy]","[Lucasfilm, Truenorth Productions, Bad Robot]",2015-12-15,7.5,2015,1868178225
4,tt2820852,190000000,1506249360,Furious 7,"[Vin Diesel, Paul Walker, Jason Statham, Miche...",[James Wan],Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,"[Action, Crime, Thriller]","[Universal Pictures, Original Film, Media Righ...",2015-04-01,7.3,2015,1316249360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1871,tt0171433,30000000,37036004,Keeping the Faith,"[Ben Stiller, Edward Norton, Jenna Elfman, Ann...",[Edward Norton],"If you have to believe in something, you may a...","Best friends since they were kids, Rabbi Jacob...",127,[Comedy],"[Spyglass Entertainment, Touchstone Pictures, ...",2000-04-14,5.7,2000,7036004
1875,tt0219854,65000000,69700000,The Kid,"[Bruce Willis, Spencer Breslin, Emily Mortimer...",[Jon Turteltaub],Nobody ever grows up quite like they imagined.,Powerful businessman Russ Duritz is self-absor...,104,"[Fantasy, Comedy, Family]",[Walt Disney Pictures],2000-07-07,5.9,2000,4700000
1877,tt0199725,20000000,27728118,Love & Basketball,"[Chris Warren, Jr., Kyla Pratt, Sanaa Lathan, ...",[Gina Prince-Bythewood],All's fair in love and basketball.,A young African-American couple navigates the ...,124,"[Action, Comedy, Drama, Romance]",[40 Acres & A Mule Filmworks],2000-04-21,7.3,2000,7728118
1883,tt0122459,24000000,36609995,Return to Me,"[David Duchovny, Minnie Driver, Carroll O'Conn...",[Bonnie Hunt],A comedy straight from the heart,It took a lot of cajoling to get Bob (Duchovny...,115,"[Romance, Comedy, Drama]","[Metro-Goldwyn-Mayer (MGM), JLT Productions]",2000-04-07,5.5,2000,12609995
1884,tt0120903,75000000,157299717,X-Men,"[Patrick Stewart, Hugh Jackman, Ian McKellen, ...",[Bryan Singer],Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,"[Adventure, Action, Science Fiction]","[Twentieth Century Fox Film Corporation, Donne...",2000-07-13,6.6,2000,82299717

In [40]:
d5.explode('genres').groupby('genres')['imdb_id'].count().sort_values(ascending = False)

genres
Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
Name: imdb_id, dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сборы?

In [41]:
 answers['13'] = '5. Peter Jackson'

In [42]:
data2.explode('director').groupby('director')['revenue'].sum().sort_values(ascending = False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 997, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [43]:
 answers['14'] = '3. Robert Rodriguez'

In [44]:
d6 = data.copy()
d6 = d6[d6.genres.str.contains('Action', na=False)]
d6['director'] = d6.director.str.split('|')
d6.explode('director').groupby(['director'])['imdb_id'].count().sort_values(ascending = False)

director
Robert Rodriguez      9
Michael Bay           7
Paul W.S. Anderson    7
Ridley Scott          6
Antoine Fuqua         6
                     ..
John Whitesell        1
Brian A Miller        1
Jon Amiel             1
Jon Avnet             1
Luis Mandoki          1
Name: imdb_id, Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [45]:
 answers['15'] = '3. Chris Hemsworth'

In [46]:
d7 = data.copy()
d7 = d7.loc[d7.release_year == 2012]
d7['cast'] = d7.cast.str.split('|')
d7.explode('cast').groupby('cast')['revenue'].sum().sort_values(ascending = False)

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Robert Downey Jr.    1519557910
Mark Ruffalo         1519557910
                        ...
Michael Nyqvist         3428048
Danny Huston            2106557
Josh Lucas              2106557
Sami Gayle              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [47]:
 answers['16'] = '3. Matt Damon'

In [48]:
d8 = data.copy()
d8 = d8[d8.budget > data.budget.mean()]
d8['cast'] = d8.cast.str.split('|')
d8.explode('cast').groupby('cast')["imdb_id"].count().sort_values(ascending = False)

cast
Matt Damon                 18
Adam Sandler               17
Angelina Jolie             16
Tom Cruise                 15
Eddie Murphy               15
                           ..
Jennifer Hudson             1
Jennifer Jason Leigh        1
Jennifer Saunders           1
Jennifer Tilly              1
Ã“lafur Darri Ã“lafsson     1
Name: imdb_id, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [49]:
 answers['17'] = '2. Action'

In [50]:
d9 = data.copy()
d9 = d9[d9.cast.str.contains('Nicolas Cage', na=False)]
d9['cast'] = d9.cast.str.split('|')
d9['genres'] = d9.genres.str.split('|')
d9.explode('genres').groupby('genres')['imdb_id'].count().sort_values(ascending = False)

genres
Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Animation           3
Family              3
Mystery             3
History             2
Horror              1
Romance             1
War                 1
Name: imdb_id, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures?

In [51]:
 answers['18'] = '1. K-19: The Widowmaker (tt0267626)'

In [52]:
d10 = data.copy()
d10['profit'] = d10['revenue'] - d10['budget']
d10 = d10[d10.production_companies.str.contains('Paramount Pictures', na=False)]
d10['production_companies'] = d10.production_companies.str.split('|')
d10.loc[d10['profit'] == d10['profit'].min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,"[Paramount Pictures, Intermedia Films, Nationa...",7/19/2002,6.0,2002,-64831034

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [53]:
 answers['19'] = '5. 2015'

In [54]:
d11 = data.copy()
d11.groupby('release_year')['revenue'].sum().sort_values(ascending=False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [55]:
 answers['20'] = '1. 2014'

In [56]:
d12 = data.copy()
d12 = d12[d12.production_companies.str.contains('Warner Bros', na=False)]
d12['production_companies'] = d12.production_companies.str.split('|')
d12['profit'] = d12['revenue'] - d12['budget']
d12.groupby('release_year')['profit'].sum().sort_values(ascending=False)

release_year
2014    2295464519
2007    2201675217
2008    2134595031
2010    1974712985
2011    1871393682
2003    1855493377
2009    1822454136
2013    1636453400
2004    1631933725
2005    1551980298
2001    1343545668
2012    1258020056
2002    1022709901
2015     870368348
2006     620170743
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [57]:
 answers['21'] = '4. Сентябрь'

In [58]:
d13 = data.copy()
d13['release_date'] = pd.to_datetime(d13['release_date'])
d13['month'] = d13.release_date.dt.month
d13

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,month
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,6.5,2015,6
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,7.1,2015,5
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,6.3,2015,3
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,7.5,2015,12
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015-04-01,7.3,2015,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1884,tt0120903,75000000,157299717,X-Men,Patrick Stewart|Hugh Jackman|Ian McKellen|Hall...,Bryan Singer,Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,Adventure|Action|Science Fiction,Twentieth Century Fox Film Corporation|Donners...,2000-07-13,6.6,2000,7
1885,tt0192255,22000000,13555988,The Little Vampire,Richard E. Grant|Jonathan Lipnicki|Jim Carter|...,Uli Edel,"They're not just best friends, they're blood b...","Based on the popular books, the story tells of...",95,Horror|Family|Foreign,New Line Cinema,2000-10-27,6.4,2000,10
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,Rene Russo|Jason Alexander|Piper Perabo|Randy ...,Des McAnuff,This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,Adventure|Animation|Action|Comedy|Family,Universal Pictures|Capella International|KC Me...,2000-06-30,4.0,2000,6
1887,tt0162983,40000000,36037909,Hanging Up,Meg Ryan|Diane Keaton|Lisa Kudrow|Walter Matth...,Diane Keaton,Every family has a few hang-ups.,A trio of sisters bond over their ambivalence ...,94,Comedy|Drama,Laurence Mark Productions|Columbia Pictures Co...,2000-02-16,5.2,2000,2
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward|Lori Heuring|Matthew Settle|Nathan ...,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,2000-07-19,5.2,2000,7

In [59]:
d13.groupby('month')['imdb_id'].count().sort_values(ascending = False)

month
9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
Name: imdb_id, dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [60]:
 answers['22'] = '2. 450'

In [61]:
d13.loc[(d13.month > 5) & (d13.month <9)]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,month
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,6.5,2015,6
6,tt1340138,155000000,440603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,Alan Taylor,Reset the future,"The year is 2029. John Connor, leader of the r...",125,Science Fiction|Action|Thriller|Adventure,Paramount Pictures|Skydance Productions,2015-06-23,5.8,2015,6
8,tt2293640,74000000,1156730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses","Minions Stuart, Kevin and Bob are recruited by...",91,Family|Animation|Adventure|Comedy,Universal Pictures|Illumination Entertainment,2015-06-17,6.5,2015,6
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,2015-06-09,8.0,2015,6
13,tt2120120,88000000,243637091,Pixels,Adam Sandler|Michelle Monaghan|Peter Dinklage|...,Chris Columbus,Game On.,Video game experts are recruited by the milita...,105,Action|Comedy|Science Fiction,Columbia Pictures|Happy Madison Productions,2015-07-16,5.8,2015,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1873,tt0160009,40000000,30199105,The Art of War,Wesley Snipes|Donald Sutherland|Maury Chaykin|...,Christian Duguay,Who is your foe?,When ruthless terrorists threaten to bring dow...,117,Action|Adventure|Thriller,Amen Ra Films|Franchise Pictures|Warner Bros.|...,2000-08-23,5.7,2000,8
1875,tt0219854,65000000,69700000,The Kid,Bruce Willis|Spencer Breslin|Emily Mortimer|Li...,Jon Turteltaub,Nobody ever grows up quite like they imagined.,Powerful businessman Russ Duritz is self-absor...,104,Fantasy|Comedy|Family,Walt Disney Pictures,2000-07-07,5.9,2000,7
1884,tt0120903,75000000,157299717,X-Men,Patrick Stewart|Hugh Jackman|Ian McKellen|Hall...,Bryan Singer,Evolution Begins,"Two mutants, Rogue and Wolverine, come to a pr...",104,Adventure|Action|Science Fiction,Twentieth Century Fox Film Corporation|Donners...,2000-07-13,6.6,2000,7
1886,tt0131704,76000000,35134820,The Adventures of Rocky & Bullwinkle,Rene Russo|Jason Alexander|Piper Perabo|Randy ...,Des McAnuff,This summer it's not the same old bull.,Rocky and Bullwinkle have been living off the ...,88,Adventure|Animation|Action|Comedy|Family,Universal Pictures|Capella International|KC Me...,2000-06-30,4.0,2000,6
1888,tt0163676,15000000,5217498,The In Crowd,Susan Ward|Lori Heuring|Matthew Settle|Nathan ...,Mary Lambert,What would you do to get in?,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,2000-07-19,5.2,2000,7

# 23. Для какого режиссера зима – самое продуктивное время года?

In [62]:
 answers['23'] = '5. Peter Jackson'

In [63]:
d14 = d13.copy()
d14 = d14.loc[(d14.month == 12) | (d14.month <3)]
d14['director'] = d14.director.str.split('|')
d14.explode('director').groupby('director')['imdb_id'].count().sort_values(ascending = False)

director
Peter Jackson        7
Steven Soderbergh    6
Clint Eastwood       6
Shawn Levy           4
Adam Shankman        4
                    ..
John Luessenhop      1
John Musker          1
John Polson          1
Callan Brunker       1
Xavier Palud         1
Name: imdb_id, Length: 358, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [64]:
 answers['24'] = '5. Four By Two Production'

In [65]:
d15 = d13.copy()
d15['len_title'] = d15.original_title.apply(lambda x:len(str(x)))
d15['production_companies'] = d15.production_companies.str.split('|')
d15.explode('production_companies').groupby('production_companies')['len_title'].mean().sort_values(ascending=False)

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Polsky Films                  46.0
Museum Canada Productions     46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
Global Entertainment Group     2.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Name: len_title, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [66]:
 answers['25'] = '3. Midnight Picture Show'

In [67]:
d16 = d13.copy()
d16['len_overview'] = d16.overview.apply(lambda x:len(str(x)))
d16['production_companies'] = d16.production_companies.str.split('|')
d16.explode('production_companies').groupby('production_companies')['len_overview'].mean().sort_values(ascending=False)

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
London Boulevard                           74.0
Henceforth                                 74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: len_overview, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу?
по vote_average

In [68]:
 answers['26'] = '1. Inside Out, The Dark Knight, 12 Years a Slave'

In [69]:
d17 = data.copy()
d17.vote_average.quantile(0.99)

7.8

In [70]:
d17 = d17[d17['vote_average'] >= 7.8]
d17

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
28,tt1895587,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,Tom McCarthy,Break the story. Break the silence.,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/2015,7.8,2015
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014
124,tt2245084,165000000,652105443,Big Hero 6,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,Don Hall|Chris Williams,From the creators of Wreck-it Ralph and Frozen,The special bond that develops between plus-si...,102,Adventure|Family|Animation|Action|Comedy,Walt Disney Pictures|Walt Disney Animation Stu...,10/24/2014,7.8,2014
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014
155,tt2980516,15000000,121201940,The Theory of Everything,Eddie Redmayne|Felicity Jones|Harry Lloyd|Davi...,James Marsh,His Mind Changed Our World. Her Love Changed His.,A look at the relationship between the famous ...,123,Drama|Romance,Working Title Films,11/26/2014,7.8,2014
177,tt2582846,12000000,305151265,The Fault in Our Stars,Shailene Woodley|Ansel Elgort|Nat Wolff|Laura ...,Josh Boone,One Sick Love Story,Despite the tumor-shrinking medical miracle th...,125,Romance|Drama,Fox 2000 Pictures|Temple Hill Entertainment|TS...,5/16/2014,7.8,2014
283,tt0485947,47000000,3547209,Mr. Nobody,Jared Leto|Diane Kruger|Linh Äan Pháº¡m|Sarah ...,Jaco Van Dormael,"Nothing is real, everything is possible.",Nemo Nobody leads an ordinary existence with h...,141,Science Fiction|Drama|Romance|Fantasy,Pan EuropÃ©enne Production|Virtual Films,9/11/2009,7.8,2009
316,tt1187043,9000000,70000000,3 Idiots,Aamir Khan|Kareena Kapoor|Madhavan|Sharman Jos...,Rajkumar Hirani,Don't BE A STUPID BE AN I.D.I.O.T.,In the tradition of â€œFerris Buellerâ€™s Day ...,170,Drama|Comedy|Romance,Vidhu Vinod Chopra Productions,12/23/2009,7.8,2009
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010
496,tt0120737,93000000,871368364,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,One ring to rule them all,"Young hobbit Frodo Baggins, after inheriting a...",178,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/2001,7.8,2001
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
863,tt0167261,79000000,926287400,The Lord of the Rings: The Two Towers,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,A New Power Is Rising.,Frodo and Sam are trekking to Mordor to destro...,179,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/2002,7.8,2002
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013
1188,tt1798709,23000000,47351251,Her,Joaquin Phoenix|Scarlett Johansson|Rooney Mara...,Spike Jonze,A Spike Jonze Love Story,"In the not so distant future, Theodore, a lone...",126,Romance|Science Fiction|Drama,Annapurna Pictures,12/18/2013,7.8,2013
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013
1205,tt1392214,46000000,122126687,Prisoners,Hugh Jackman|Jake Gyllenhaal|Paul Dano|Maria B...,Denis Villeneuve,Every moment matters.,When Keller Dover's daughter and her friend go...,153,Drama|Thriller|Crime,Alcon Entertainment|Madhouse Entertainment|8:3...,9/18/2013,7.8,2013
1213,tt0790636,5000000,55198285,Dallas Buyers Club,Matthew McConaughey|Jennifer Garner|Jared Leto...,Jean-Marc VallÃ©e,Sometimes it takes a hustler to change the world,Loosely based on the true-life tale of Ron Woo...,117,Drama|History,Universal Studios|Universal Pictures|Voltage P...,9/7/2013,7.8,2013
1444,tt0482571,40000000,109676311,The Prestige,Hugh Jackman|Christian Bale|Michael Caine|Scar...,Christopher Nolan,Are You Watching Closely?,A mysterious story of two magicians whose inte...,130,Drama|Mystery|Thriller,Touchstone Pictures|Syncopy,10/19/2006,7.8,2006
1563,tt0338013,20000000,72258126,Eternal Sunshine of the Spotless Mind,Jim Carrey|Kate Winslet|Elijah Wood|Mark Ruffa...,Michel Gondry,I already forget how I used to feel about you.,"Joel Barish, heartbroken that his girlfriend u...",108,Science Fiction|Drama|Romance,Anonymous Content|This Is That Productions|Foc...,3/19/2004,7.8,2004
1688,tt0469494,25000000,76181545,There Will Be Blood,Daniel Day-Lewis|Paul Dano|Dillon Freasier|Cia...,Paul Thomas Anderson,There Will Be Greed. There Will Be Vengeance.,"When ruthless oil prospector, Daniel Plainview...",158,Drama,Miramax Films|Ghoulardi Film Company|Paramount...,12/28/2007,7.8,2007
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000

In [71]:
d17.loc[(d17.original_title == '12 years a Slave')|(d17.original_title == 'The Dark Knight')|(d17.original_title == 'Inside Out')]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [72]:
 answers['27'] = '5. Daniel Radckiffe & Rupert Grint'

In [73]:
d18 = data.copy()
d18['cast'] = d18.cast.str.split('|')
d18.cast = d18.cast.apply(lambda x: list(it.combinations(sorted(x), 2)))
d18.explode('cast').cast.value_counts()

(Daniel Radcliffe, Emma Watson)        8
(Daniel Radcliffe, Rupert Grint)       8
(Emma Watson, Rupert Grint)            8
(Ben Stiller, Owen Wilson)             6
(Helena Bonham Carter, Johnny Depp)    6
                                      ..
(Hugh Jackman, Rooney Mara)            1
(Eve Hewson, Kerry Condon)             1
(Christine Taylor, John Krasinski)     1
(George Clooney, Shailene Woodley)     1
(Emjay Anthony, Toni Collette)         1
Name: cast, Length: 17943, dtype: int64

In [74]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': '5. Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': '2. Gods and Generals  (tt0279111)',
 '3': '3. Winnie the Pooh (tt1449283)',
 '4': '2. 110',
 '5': '1. 107',
 '6': '5. Avatar (tt0499549)',
 '7': '5. The Lone Ranger  (tt1210819)',
 '8': '1. 1478 ',
 '9': '4. The Dark Knight (tt0468569)',
 '10': '5. The Lone Ranger (tt1210819)',
 '11': '3. Drama',
 '12': '1. Drama',
 '13': '5. Peter Jackson',
 '14': '3. Robert Rodriguez',
 '15': '3. Chris Hemsworth',
 '16': '3. Matt Damon',
 '17': '2. Action',
 '18': '1. K-19: The Widowmaker (tt0267626)',
 '19': '5. 2015',
 '20': '1. 2014',
 '21': '4. Сентябрь',
 '22': '2. 450',
 '23': '5. Peter Jackson',
 '24': '5. Four By Two Production',
 '25': '3. Midnight Picture Show',
 '26': '1. Inside Out, The Dark Knight, 12 Years a Slave',
 '27': '5. Daniel Radckiffe & Rupert Grint'}

In [75]:
# и убедиться что ни чего не пропустил)
len(answers)

27